name: Publish to GCR

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  IMAGE: afk-manager

jobs:
  setup-build-publish:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - run: |-
          gcloud --quiet auth configure-docker
      - name: Build
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$IMAGE:${GITHUB_SHA::7}" \
            .
      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:${GITHUB_SHA::7}"
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    needs: setup-build-publish

    steps:
      - uses: actions/checkout@v2
        with:
          repository: SamMauldin/sam-kube
          token: ${{ secrets.GH_TOKEN }}

      - run: 'curl -fsSL https://get.pulumi.com | sh'

      - run: '~/.pulumi/bin/pulumi config -s dev set $IMAGE-image gcr.io/$PROJECT_ID/$IMAGE:${GITHUB_SHA::7}'
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - run: 'git config user.email "deploy@mauldin.me"'
      - run: 'git config user.name "Deploy Integration"'

      - run: 'git commit -a -m "Bump $IMAGE to ${GITHUB_SHA::7}";'

      - run: 'git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/SamMauldin/sam-kube.git'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - run: 'git push origin master'
